POST http://localhost:3003/api/blogs/
Content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imphc2ltIiwiaWQiOiI2MDJhNTcwYWEwZWE1ZDAyNmNjYmMxNTkiLCJpYXQiOjE2MTMzOTA4MzR9.KssIWRSVd5vSjkWY5j7WVv-pmkzlikIcXQFXU6P6HKk

{
  "title": "React is poggers",
  "author": "JASIM AUTHOR",
  "url": "https://jasim-bloggers.com",
  "likes": 123
}