POST http://localhost:3003/api/blogs/6022b33401e03143cc943cd6
Content-type: application/json

{
  "title": "Kapteeni kalsari2",
  "author": "testaaja toivonen",
  "url": "http:://kallenkirjat.com",
  "likes": 555
}